import SwiftUI

/// TipMe's visual language in one place.
///
/// The brief asked for something that reads like Strike: bold numerals doing
/// the talking, near-black chrome, one accent color, no visual noise
/// competing with a balance or an amount. Every screen in `App/TipMe` and
/// `App/Shared` draws from here rather than ad hoc `.foregroundColor` calls,
/// so the app reads as one product rather than a pile of screens.
enum Theme {

    // MARK: - Color

    /// Bitcoin orange as the single accent — used sparingly, for the primary
    /// action on each screen and nothing else. A screen with three accented
    /// elements has no accent at all.
    static let accent = Color(light: (0.90, 0.42, 0.02), dark: (1.00, 0.55, 0.10))

    static let background = Color(light: (0.98, 0.98, 0.98), dark: (0.05, 0.05, 0.06))
    static let surface = Color(light: (1.00, 1.00, 1.00), dark: (0.11, 0.11, 0.12))
    static let surfaceRaised = Color(light: (0.96, 0.96, 0.97), dark: (0.16, 0.16, 0.18))

    static let textPrimary = Color(light: (0.07, 0.07, 0.08), dark: (0.97, 0.97, 0.98))
    static let textSecondary = Color(light: (0.45, 0.45, 0.48), dark: (0.62, 0.62, 0.66))
    static let textTertiary = Color(light: (0.65, 0.65, 0.68), dark: (0.42, 0.42, 0.46))

    static let positive = Color(light: (0.13, 0.55, 0.25), dark: (0.30, 0.78, 0.42))
    static let negative = Color(light: (0.75, 0.15, 0.15), dark: (0.92, 0.35, 0.35))
    static let warning = Color(light: (0.70, 0.45, 0.02), dark: (0.95, 0.65, 0.15))

    static let divider = Color(light: (0.88, 0.88, 0.90), dark: (0.22, 0.22, 0.24))

    // MARK: - Type

    /// The one number the eye should land on first. Rounded design leans
    /// friendly rather than clinical for a figure that is, after all, someone's
    /// money.
    static func balance(_ size: CGFloat = 52) -> Font {
        .system(size: size, weight: .bold, design: .rounded).monospacedDigit()
    }

    static let amountLarge = Font.system(size: 34, weight: .semibold, design: .rounded).monospacedDigit()
    static let amountMedium = Font.system(size: 20, weight: .semibold, design: .rounded).monospacedDigit()
    static let title = Font.system(size: 22, weight: .bold)
    static let headline = Font.system(size: 17, weight: .semibold)
    static let body = Font.system(size: 16, weight: .regular)
    static let caption = Font.system(size: 13, weight: .regular)
    static let label = Font.system(size: 12, weight: .semibold).smallCaps()

    // MARK: - Metrics

    static let cornerRadius: CGFloat = 20
    static let cornerRadiusSmall: CGFloat = 12
    static let spacing: CGFloat = 16
    static let spacingSmall: CGFloat = 8
    static let spacingLarge: CGFloat = 28
}

extension Color {
    /// Defines a color for both appearances without needing an asset catalog —
    /// this repository's project is generated by XcodeGen from source folders,
    /// and keeping every design token in Swift means no separate catalog file
    /// can drift out of sync with it.
    init(light: (Double, Double, Double), dark: (Double, Double, Double)) {
        self.init(uiColor: UIColor { trait in
            let (r, g, b) = trait.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: r, green: g, blue: b, alpha: 1)
        })
    }
}
