import SwiftUI

/// TipMe's visual language in one place.
///
/// Pure black and white, Strike-style: there is no hue anywhere in this file.
/// The "accent" used for every primary action is simply the inverse of the
/// surface it sits on — `Theme.accent` renders as near-black on a white
/// background and near-white on a black one, with `Theme.onAccent` as its
/// exact complement for whatever sits on top of it (button text, an icon).
/// Every screen in `App/TipMe` and `App/Shared` draws from here rather than
/// ad hoc `.foregroundColor` calls, so the app reads as one product.
enum Theme {

    // MARK: - Color

    /// The single "accent": black in light mode, white in dark mode. Used for
    /// the primary action on each screen and nothing else — a screen with
    /// three accented elements has no accent at all.
    static let accent = Color(light: (0.04, 0.04, 0.05), dark: (1.00, 1.00, 1.00))
    /// The exact complement of `accent`, for whatever renders on top of it.
    static let onAccent = Color(light: (1.00, 1.00, 1.00), dark: (0.04, 0.04, 0.05))

    /// True white / true black — the flat, high-contrast ground this whole
    /// palette is built from.
    static let background = Color(light: (1.00, 1.00, 1.00), dark: (0.00, 0.00, 0.00))
    static let surface = Color(light: (0.965, 0.965, 0.968), dark: (0.067, 0.067, 0.071))
    static let surfaceRaised = Color(light: (0.925, 0.925, 0.930), dark: (0.110, 0.110, 0.117))

    static let textPrimary = Color(light: (0.04, 0.04, 0.05), dark: (1.00, 1.00, 1.00))
    static let textSecondary = Color(light: (0.42, 0.42, 0.44), dark: (0.60, 0.60, 0.62))
    static let textTertiary = Color(light: (0.67, 0.67, 0.69), dark: (0.30, 0.30, 0.31))

    /// Semantic colors, kept deliberately muted and used only for a status
    /// signal (an incoming amount, a warning icon) — never as decoration, and
    /// never as a substitute for `accent`.
    static let positive = Color(light: (0.15, 0.55, 0.28), dark: (0.24, 0.75, 0.42))
    static let negative = Color(light: (0.72, 0.19, 0.19), dark: (0.85, 0.34, 0.34))
    static let warning = Color(light: (0.62, 0.44, 0.05), dark: (0.85, 0.62, 0.20))

    static let divider = Color(light: (0.90, 0.90, 0.92), dark: (0.125, 0.125, 0.130))

    // MARK: - Type

    /// The one number the eye should land on first.
    static func balance(_ size: CGFloat = 48) -> Font {
        .system(size: size, weight: .heavy, design: .rounded).monospacedDigit()
    }

    static let amountLarge = Font.system(size: 32, weight: .bold, design: .rounded).monospacedDigit()
    static let amountMedium = Font.system(size: 19, weight: .bold, design: .rounded).monospacedDigit()
    static let title = Font.system(size: 22, weight: .bold)
    static let headline = Font.system(size: 16, weight: .semibold)
    static let body = Font.system(size: 15.5, weight: .regular)
    static let caption = Font.system(size: 12.5, weight: .regular)
    static let label = Font.system(size: 11, weight: .semibold).smallCaps()

    // MARK: - Metrics

    static let cornerRadius: CGFloat = 22
    static let cornerRadiusSmall: CGFloat = 14
    static let spacing: CGFloat = 16
    static let spacingSmall: CGFloat = 8
    static let spacingLarge: CGFloat = 28
}

extension Color {
    /// Defines a color for both appearances without needing an asset catalog —
    /// this repository's project is generated by XcodeGen from source folders,
    /// and keeping every design token in Swift means no separate catalog file
    /// can drift out of sync with it.
    init(light: (Double, Double, Double), dark: (Double, Double, Double)) {
        self.init(uiColor: UIColor { trait in
            let (r, g, b) = trait.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: r, green: g, blue: b, alpha: 1)
        })
    }
}
