import SwiftUI

/// TipMe's visual language in one place.
///
/// White and near-black for the surface and text -- readable, restrained,
/// Apple-Wallet-plain -- and one warm coral-red (`Theme.brand`, the app
/// icon's own color) carried through every interactive surface: nav tint,
/// icon badges, selected states, the primary button. This used to reserve
/// that color for a single button and run everything else in monochrome;
/// that read as generic rather than as TipMe, so `accent` now *is* `brand`
/// rather than its own near-black. Every screen in `App/TipMe` and
/// `App/Shared` draws from here rather than ad hoc `.foregroundColor` calls,
/// so the app reads as one product.
enum Theme {

    // MARK: - Color

    /// The "accent": TipMe's own brand color, not a neutral black/white one.
    /// Used for a `.tint`, a step marker, a selected segment -- anything that
    /// should read as "this app" rather than as system chrome.
    static let accent: Color = brand
    /// The exact complement of `accent`, for whatever renders on top of it.
    static let onAccent: Color = onBrand

    /// The app icon's own color, and now the color behind almost every
    /// interactive element -- nav tint, icon badges, a primary action, the
    /// moment money actually moves. Warm rather than the money-green or
    /// payment-blue every other wallet already owns; a little brighter in
    /// dark mode so it still reads as vivid against true black rather than
    /// receding into it.
    static let brand = Color(light: (1.00, 0.28, 0.36), dark: (1.00, 0.34, 0.42))
    /// White in both modes -- `brand` is saturated/dark enough at both
    /// values above for white text to sit on it either way, so this never
    /// needs to flip the way `onAccent` does.
    static let onBrand = Color(red: 1.00, green: 1.00, blue: 1.00)

    /// True white / true black — the flat, high-contrast ground this whole
    /// palette is built from.
    static let background = Color(light: (1.00, 1.00, 1.00), dark: (0.00, 0.00, 0.00))
    static let surface = Color(light: (0.965, 0.965, 0.968), dark: (0.067, 0.067, 0.071))
    static let surfaceRaised = Color(light: (0.925, 0.925, 0.930), dark: (0.110, 0.110, 0.117))

    static let textPrimary = Color(light: (0.04, 0.04, 0.05), dark: (1.00, 1.00, 1.00))
    static let textSecondary = Color(light: (0.42, 0.42, 0.44), dark: (0.60, 0.60, 0.62))
    static let textTertiary = Color(light: (0.67, 0.67, 0.69), dark: (0.30, 0.30, 0.31))

    /// Semantic colors, kept deliberately muted and used only for a status
    /// signal (an incoming amount, a warning icon) — never as decoration, and
    /// never as a substitute for `accent`.
    static let positive = Color(light: (0.15, 0.55, 0.28), dark: (0.24, 0.75, 0.42))
    static let negative = Color(light: (0.72, 0.19, 0.19), dark: (0.85, 0.34, 0.34))
    static let warning = Color(light: (0.62, 0.44, 0.05), dark: (0.85, 0.62, 0.20))

    static let divider = Color(light: (0.90, 0.90, 0.92), dark: (0.125, 0.125, 0.130))

    // MARK: - Type

    /// The one number the eye should land on first.
    static func balance(_ size: CGFloat = 48) -> Font {
        .system(size: size, weight: .heavy, design: .rounded).monospacedDigit()
    }

    static let amountLarge = Font.system(size: 32, weight: .bold, design: .rounded).monospacedDigit()
    static let amountMedium = Font.system(size: 19, weight: .bold, design: .rounded).monospacedDigit()
    static let title = Font.system(size: 22, weight: .bold)
    static let headline = Font.system(size: 16, weight: .semibold)
    static let body = Font.system(size: 15.5, weight: .regular)
    static let caption = Font.system(size: 12.5, weight: .regular)
    static let label = Font.system(size: 11, weight: .semibold).smallCaps()

    // MARK: - Motion

    /// The one spring behind every state change in the app -- a screen
    /// swapping content, a row appearing, a value updating. Every screen
    /// using the same curve is what makes switching between them feel like
    /// one product instead of a collection of separately-tuned ones; see
    /// `PressableStyle` for the matching tap feedback.
    static let motion: Animation = .spring(response: 0.38, dampingFraction: 0.86)

    // MARK: - Metrics

    static let cornerRadius: CGFloat = 22
    static let cornerRadiusSmall: CGFloat = 14
    static let spacing: CGFloat = 16
    static let spacingSmall: CGFloat = 8
    static let spacingLarge: CGFloat = 28
}

extension Color {
    /// Defines a color for both appearances without needing an asset catalog —
    /// this repository's project is generated by XcodeGen from source folders,
    /// and keeping every design token in Swift means no separate catalog file
    /// can drift out of sync with it.
    init(light: (Double, Double, Double), dark: (Double, Double, Double)) {
        self.init(uiColor: UIColor { trait in
            let (r, g, b) = trait.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: r, green: g, blue: b, alpha: 1)
        })
    }
}
