#!/usr/bin/env bash
#
# Turns .env into Config/Secrets.xcconfig, which Xcode feeds into Info.plist,
# which AppConfiguration reads at launch.
#
# Run after editing .env:
#   ./Scripts/make-xcconfig.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT="$ROOT/Config/Secrets.xcconfig"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: no .env found. Copy .env.example to .env and fill it in." >&2
  exit 1
fi

{
  echo "// Generated by Scripts/make-xcconfig.sh — do not edit, do not commit."
  echo "SLASH = /"
  while IFS= read -r line || [[ -n "$line" ]]; do
    # Skip blanks and comments.
    [[ -z "${line// }" ]] && continue
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" != *=* ]] && continue

    key="${line%%=*}"
    value="${line#*=}"
    key="$(echo "$key" | xargs)"

    # Registry-side settings never belong in the app bundle.
    case "$key" in
      REGISTRY_*) continue ;;
    esac

    # xcconfig reads "//" as a comment, which would truncate every URL.
    value="${value//\/\//\$(SLASH)\$(SLASH)}"
    echo "$key = $value"
  done < "$ENV_FILE"
} > "$OUT"

echo "wrote $OUT"
